name: Build pages

on:
  push:
    paths-ignore:
      - 'docs/**'
      - 'data/**'
    branches:
      - main
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

env:
  DLB_BOT_EMAIL: ${{ secrets.DLB_BOT_EMAIL }}
  DLB_BOT_TOKEN: ${{ secrets.DLB_BOT_TOKEN }}
  DLB_BOT_USERNAME: ${{ secrets.DLB_BOT_USERNAME }}
  SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.DLB_BOT_TOKEN }}
        lfs: true
        submodules: true

    - uses: digital-land/digital-land-build-action@v1
      with:
        clobber-first: true

    - name: Notify slack success
      if: success()
      uses: digital-land/github-action-slack-notify-build@main
      with:
        message_id: ${{ steps.slack.outputs.message_id }}
        channel: dl-github
        status: SUCCESS
        color: good

    - name: Notify slack fail
      if: failure()
      uses: digital-land/github-action-slack-notify-build@main
      with:
        message_id: ${{ steps.slack.outputs.message_id }}
        channel: dl-github
        status: FAILED
        color: danger

    - name: Notify slack fail
      if: failure()
      uses: digital-land/github-action-slack-notify-build@main
      with:
        message_id: ${{ steps.slack.outputs.message_id }}
        channel: dl-developer
        status: FAILED
        color: danger
